import crypto from 'crypto'
import { createSupabaseApiClient } from '../../../lib/supabaseServerClient'
import supabaseAdmin from '../../../lib/supabaseAdminClient'

// Generates a securely random temporary password (URL-safe, 24+ chars).
function generateTempPassword() {
  return crypto.randomBytes(18).toString('base64url')
}

// Server-side Company Provisioning API.
//
// Current scope (per task): validate the request, verify the caller is an
// authenticated super_admin, and return structured responses. Actual
// provisioning (company row, Auth user, users row, company_settings,
// subscription) is intentionally NOT implemented yet — this endpoint is a
// scaffold for that future work. It does not replace or remove the existing
// client-side "Add Company" flow in pages/admin/companies.js.
export default async function handler(req, res) {
  if (req.method !== 'POST') {
    res.setHeader('Allow', 'POST')
    return res.status(405).json({ success: false, error: 'Method not allowed' })
  }

  // ── Authenticate the caller from their session cookies ──
  const supabase = createSupabaseApiClient(req, res)

  const { data: { user }, error: authError } = await supabase.auth.getUser()
  if (authError || !user) {
    return res.status(401).json({ success: false, error: 'Unauthorized' })
  }

  // ── Verify role: super_admin only ──
  const { data: profile, error: profileError } = await supabase
    .from('users')
    .select('role')
    .eq('id', user.id)
    .maybeSingle()

  if (profileError) {
    return res.status(500).json({ success: false, error: 'Failed to verify user role' })
  }

  if (!profile || profile.role !== 'super_admin') {
    return res.status(403).json({ success: false, error: 'Forbidden — super_admin role required' })
  }

  // ── Validate request body ──
  const {
    name,
    slug,
    owner_email,
    owner_name,
    whatsapp_number,
    phone,
    primary_color,
    timezone,
    currency,
    logo_url,
    subscription_plan_id,
    owner_temp_password,
  } = req.body || {}

  if (!name || typeof name !== 'string' || !name.trim()) {
    return res.status(400).json({ success: false, error: 'Company name is required' })
  }
  if (!slug || typeof slug !== 'string' || !slug.trim()) {
    return res.status(400).json({ success: false, error: 'Company slug is required' })
  }
  if (!owner_email || typeof owner_email !== 'string' || !owner_email.trim()) {
    return res.status(400).json({ success: false, error: 'Owner email is required' })
  }
  if (!whatsapp_number || typeof whatsapp_number !== 'string' || !whatsapp_number.trim()) {
    return res.status(400).json({ success: false, error: 'WhatsApp number is required' })
  }

  // ── Step 1: create the company record only ──
  // Owner Auth user, users row, company_settings, and subscription assignment
  // are intentionally deferred to later provisioning steps.
  try {
    const { data: company, error: insertError } = await supabaseAdmin
      .from('companies')
      .insert({
        name: name.trim(),
        slug: slug.trim(),
        is_active: true,
      })
      .select('id')
      .single()

    if (insertError) {
      return res.status(500).json({
        success: false,
        error: `Failed to create company: ${insertError.message}`,
      })
    }

    // ── Step 2: create the owner's Supabase Auth account ──
    // Note: the company row above already exists at this point. If Auth
    // creation fails we stop here and report the failure — the company
    // record is left in place for the next provisioning attempt/step
    // (no users row, company_settings, or subscription exist yet either way).
    // Prefer the password generated by the caller (Super Admin UI); only
    // fall back to server-side generation if none was supplied.
    const tempPassword =
      owner_temp_password && typeof owner_temp_password === 'string' && owner_temp_password.length >= 8
        ? owner_temp_password
        : generateTempPassword()

    const { data: authData, error: authCreateError } = await supabaseAdmin.auth.admin.createUser({
      email: owner_email.trim(),
      password: tempPassword,
      email_confirm: true,
      user_metadata: { must_change_password: true },
    })

    if (authCreateError) {
      // ── Rollback: delete the orphaned company record ──
      const { error: rollbackError } = await supabaseAdmin
        .from('companies')
        .delete()
        .eq('id', company.id)

      return res.status(500).json({
        success: false,
        error: `Failed to create owner authentication account: ${authCreateError.message}`,
        rollbackFailed: !!rollbackError,
      })
    }

    const authUserId = authData.user.id

    // ── Step 3: create the application user profile ──
    // Upsert (not insert): migration 015 auto-creates a default
    // public.users row via an auth.users trigger the instant
    // auth.admin.createUser() above runs, so a plain insert here would
    // fail on the primary key. Upserting fills in the real company_id /
    // role / full_name on top of that default row.
    const { error: usersInsertError } = await supabaseAdmin
      .from('users')
      .upsert(
        {
          id: authUserId,
          company_id: company.id,
          role: 'company_owner',
          full_name: owner_name,
          email: owner_email.trim(),
          is_active: true,
        },
        { onConflict: 'id' }
      )

    if (usersInsertError) {
      // Rollback: Auth user, then company. Track failures independently.
      const { error: authDeleteError } = await supabaseAdmin.auth.admin.deleteUser(authUserId)
      const { error: companyDeleteError } = await supabaseAdmin
        .from('companies')
        .delete()
        .eq('id', company.id)

      return res.status(500).json({
        success: false,
        error: `Failed to create user profile: ${usersInsertError.message}`,
        rollbackFailed: !!(authDeleteError || companyDeleteError),
      })
    }

    // ── Link the company to its owner ──
    const { error: ownerLinkError } = await supabaseAdmin
      .from('companies')
      .update({ owner_user_id: authUserId })
      .eq('id', company.id)

    if (ownerLinkError) {
      // Rollback: users row, then Auth user, then company.
      const { error: usersDeleteError } = await supabaseAdmin
        .from('users')
        .delete()
        .eq('id', authUserId)
      const { error: authDeleteError } = await supabaseAdmin.auth.admin.deleteUser(authUserId)
      const { error: companyDeleteError } = await supabaseAdmin
        .from('companies')
        .delete()
        .eq('id', company.id)

      return res.status(500).json({
        success: false,
        error: `Failed to link owner to company: ${ownerLinkError.message}`,
        rollbackFailed: !!(usersDeleteError || authDeleteError || companyDeleteError),
      })
    }

    // ── Step 4: create company_settings ──
    const { error: settingsError } = await supabaseAdmin
      .from('company_settings')
      .insert({
        company_id: company.id,
        whatsapp_number: whatsapp_number.trim(),
        phone: phone || null,
        primary_color: primary_color || '#0A1F44',
        timezone: timezone || 'Asia/Karachi',
        currency: currency || 'PKR',
        logo_url: logo_url || null,
      })

    if (settingsError) {
      // Rollback: company_settings (if partially created), users row, Auth user, company.
      const { error: settingsDeleteError } = await supabaseAdmin
        .from('company_settings')
        .delete()
        .eq('company_id', company.id)
      const { error: usersDeleteError } = await supabaseAdmin
        .from('users')
        .delete()
        .eq('id', authUserId)
      const { error: authDeleteError } = await supabaseAdmin.auth.admin.deleteUser(authUserId)
      const { error: companyDeleteError } = await supabaseAdmin
        .from('companies')
        .delete()
        .eq('id', company.id)

      return res.status(500).json({
        success: false,
        error: `Failed to create company settings: ${settingsError.message}`,
        rollbackFailed: !!(settingsDeleteError || usersDeleteError || authDeleteError || companyDeleteError),
      })
    }

    // ── Step 5: assign subscription plan, if one was selected ──
    if (subscription_plan_id) {
      const { error: subscriptionError } = await supabaseAdmin
        .from('company_subscriptions')
        .insert({
          company_id: company.id,
          plan_id: subscription_plan_id,
          status: 'active',
        })

      if (subscriptionError) {
        // Rollback: subscription (if partially created), company_settings, users row, Auth user, company.
        const { error: subDeleteError } = await supabaseAdmin
          .from('company_subscriptions')
          .delete()
          .eq('company_id', company.id)
        const { error: settingsDeleteError } = await supabaseAdmin
          .from('company_settings')
          .delete()
          .eq('company_id', company.id)
        const { error: usersDeleteError } = await supabaseAdmin
          .from('users')
          .delete()
          .eq('id', authUserId)
        const { error: authDeleteError } = await supabaseAdmin.auth.admin.deleteUser(authUserId)
        const { error: companyDeleteError } = await supabaseAdmin
          .from('companies')
          .delete()
          .eq('id', company.id)

        return res.status(500).json({
          success: false,
          error: `Failed to create subscription: ${subscriptionError.message}`,
          rollbackFailed: !!(
            subDeleteError ||
            settingsDeleteError ||
            usersDeleteError ||
            authDeleteError ||
            companyDeleteError
          ),
        })
      }
    }

    // The temporary password is never persisted anywhere (not in the
    // database, not logged) — it is returned only in this one-time success
    // response so the caller can display it to the Super Admin once.
    return res.status(201).json({
      success: true,
      companyId: company.id,
      authUserId,
      tempPassword,
      message: 'Company, owner authentication account, and user profile created successfully.',
    })
  } catch (err) {
    return res.status(500).json({
      success: false,
      error: err?.message || 'Unexpected error while creating company',
    })
  }
}
